conflicting_attributes_yes = {
    "yellow_skin": ["pink_skin", "blue_skin", "green_skin"],
    "pink_skin": ["yellow_skin", "blue_skin", "green_skin"],
    "blue_skin": ["pink_skin", "yellow_skin", "green_skin"],
    "green_skin": ["pink_skin", "blue_skin", "yellow_skin"],
    "is_dragon": ["is_cat"],
    "is_cat": ["is_dragon"],
    "white_hair": [
        "dark_hair",
        "blue_hair",
        "blond_hair",
        "ever_had_blond_hair",
        "multi_colored_hair",
        "have_hair",
    ],
    "dark_hair": [
        "blue_hair",
        "white_hair",
        "blond_hair",
        "ever_had_blond_hair",
        "multi_colored_hair",
        "have_hair",
    ],
    "blue_hair": [
        "dark_hair",
        "white_hair",
        "blond_hair",
        "ever_had_blond_hair",
        "multi_colored_hair",
        "have_hair",
    ],
    "blond_hair": [
        "dark_hair",
        "blue_hair",
        "white_hair",
        "multi_colored_hair",
        "have_hair",
    ],
    "from_seven_deadly_sins": [
        "from_jujutsu_kaisen",
        "from_one_piece",
        "from_one_punch_man",
        "from_dragon_ball",
        "from_naruto",
        "from_attack_on_titan",
        "from_tom_and_jerry",
        "in_detective_story",
    ],
    "from_jujutsu_kaisen": [
        "from_seven_deadly_sins",
        "from_one_piece",
        "from_one_punch_man",
        "from_dragon_ball",
        "from_naruto",
        "from_attack_on_titan",
        "from_tom_and_jerry",
        "in_detective_story",
    ],
    "from_one_piece": [
        "from_seven_deadly_sins",
        "from_jujutsu_kaisen",
        "from_one_punch_man",
        "from_dragon_ball",
        "from_naruto",
        "from_attack_on_titan",
        "from_tom_and_jerry",
        "in_detective_story",
    ],
    "from_one_punch_man": [
        "from_seven_deadly_sins",
        "from_jujutsu_kaisen",
        "from_one_piece",
        "from_dragon_ball",
        "from_naruto",
        "from_attack_on_titan",
        "from_tom_and_jerry",
        "in_detective_story",
    ],
    "from_dragon_ball": [
        "from_seven_deadly_sins",
        "from_jujutsu_kaisen",
        "from_one_piece",
        "from_one_punch_man",
        "from_naruto",
        "from_attack_on_titan",
        "from_tom_and_jerry",
        "in_detective_story",
    ],
    "from_naruto": [
        "from_seven_deadly_sins",
        "from_jujutsu_kaisen",
        "from_one_piece",
        "from_one_punch_man",
        "from_dragon_ball",
        "from_attack_on_titan",
        "from_tom_and_jerry",
        "in_detective_story",
    ],
    "from_attack_on_titan": [
        "from_seven_deadly_sins",
        "from_jujutsu_kaisen",
        "from_one_piece",
        "from_one_punch_man",
        "from_dragon_ball",
        "from_naruto",
        "from_tom_and_jerry",
        "in_detective_story",
    ],
    "from_tom_and_jerry": [
        "from_seven_deadly_sins",
        "from_jujutsu_kaisen",
        "from_one_piece",
        "from_one_punch_man",
        "from_dragon_ball",
        "from_naruto",
        "from_attack_on_titan",
        "in_detective_story",
    ],
    "in_detective_story": [
        "from_seven_deadly_sins",
        "from_jujutsu_kaisen",
        "from_one_piece",
        "from_one_punch_man",
        "from_dragon_ball",
        "from_naruto",
        "from_attack_on_titan",
        "from_tom_and_jerry",
    ],
    "is_angel": ["is_saiyan", "is_god_of_destruction", "is_animal"],
    "is_saiyan": ["is_angel", "is_god_of_destruction", "is_animal"],
    "is_animal": ["is_saiyan", "is_god_of_destruction", "is_angel"],
    "is_god_of_destruction": [
        "is_saiyan",
        "is_angel",
        "is_animal",
    ],
    "is_detective": ["is_animal"],
    "wear_orange_suits": ["wear_green_jacket"],
    "wear_green_jacket": ["wear_orange_suitszzzz"],
}

conflicting_attributes_no = {
    "in_detective_story": ["is_detective"],
    "wear_clothes": [
        "wear_green_jacket",
        "wear_orange_suits",
    ],
    "have_hair": [
        "multi_colored_hair",
        "dark_hair",
        "special_hair_color",
        "long_hair",
        "blue_hair",
        "white_hair",
        "blond_hair",
        "ever_had_blond_hair",
    ],
    "special_hair_color": [
        "multi_colored_hair",
        "blue_hair",
        "white_hair",
        "blond_hair",
    ],
    "have_legs": ["walk_on_two_legs"],
    "is_animal": ["is_cat", "is_dragon"],
    "from_attack_on_titan": ["use_a_hook"],
}
